server.port=${PORT:8080}
spring.application.name=inventarios
# Añade esto

# Driver y URL para PostgreSQL (Neon)
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configuración de Hibernate para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.banner-mode=off

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# SendGrid (deshabilitado)
sendgrid.api.key=dummy_key_123

# Mailtrap Configuration (DESCOMENTADO)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# PaypalConfiguration


paypal.client.id=${PAYPAL_CLIENT_ID}
paypal.client.secret=${PAYPAL_CLIENT_SECRET}
paypal.mode=sandbox
spring.profiles.active=dev

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

langchain4j.google-ai-gemini.chat-model.api-key=GOOGLE_AI_API_KEY
langchain4j.google-ai-gemini.chat-model.model-name=gemini-1.5-flash