# Archivo .env (LOCAL - NUNCA LO SUBAS)
DB_USER=root
DB_PASSWORD=stardust
MAIL_USER=abe8c22a82ead1
MAIL_PASSWORD=5e20317afaf48d
PAYPAL_CLIENT_ID=AdOmboK8UjAkJgxjG3gC5D1Ia5HKCG50OQLWt5zqAK4CvOuWlHdMaD7t-CLrEihvPFpYgehNDbX6v7sc
PAYPAL_CLIENT_SECRET=AdOmboK8UjAkJgxjG3gC5D1Ia5HKCG